name="Config"

[Unit]
id=
name=
class_map=

[[Users]]
name=
prefered_bike=
id=
email=
password=
forbiden_bikes =

[[Users]]
name=
prefered_bike=
id=
email=
password=

[[Classes]]
day_of_week=
time=

[[Classes]]
day_of_week=
time=

